### ISSUE TITLE
Some email bodies have certain elements removed

### ISSUE THREAD

**Issue by scottrpaterson** [KB-Support/kb-support#107]
Sometimes the email body gets cut off. For example this always happens to WP password emails:

This is what the ticket body contains:  (Notice the reset link is missing)
![1](https://user-images.githubusercontent.com/11578353/41733448-1bb0b844-7541-11e8-83df-cf5f72b98a26.png)

This is what the email actually contains:
![2](https://user-images.githubusercontent.com/11578353/41733521-4a76d00a-7541-11e8-984b-308a7242c66a.png)

**Comment by mikeyhoward1977** [comment]
As this is related to the Email Support extension I have created an issue within that private repository, and just pushed a fix to the repo.

I will close this issue. An updated version of that extension will be released later today with the resolution
