### ISSUE TITLE
EDD extension - search EDD customers

### ISSUE THREAD

**Issue by scottrpaterson** [KB-Support/kb-support#73]
With the EDD extension, there is already a post type for customers.

It would be nice if there was the option of replacing the kbs-customers post type, or perhaps merging the two lists together.

Why this is important: If you go to Tickets -> Open Ticket, you can only assign it to customers that have previously submitted a support request.

**Comment by mikeyhoward1977** [comment]
This will most likely be an update to the EDD extension that will see us sync the customers in the same way we do downloads, but leaving here until investigation complete in case additional filters or hooks are required.

**Comment by mikeyhoward1977** [comment]
This enhancement has been included within the next release of the EDD extension which we will push later this week

**Comment by mikeyhoward1977** [comment]
Sorry - that should have said next week... Currently planned for 22nd March
