### ISSUE TITLE
Ticket Received Email - Stop Emails to Admin - Infinite Loop

### ISSUE THREAD

**Issue by scottrpaterson** [KB-Support/kb-support#84]
Let's say my admin email is: support@example.com

I want to have notifications on my site setup for a number of things like affiliate registration, etc. that will send an email to support@example.com; as this is the only way to get notified of an activity without using a separate email account.

However if I am using the email pipping add-on to pull emails from support@example.com, and also have the 'Ticket Logged' auto reply enabled, then this will cause an infinite email loop to happen.

I think the solution for this is to have a setting that will not send 'Ticket Received' emails to the 'Email Settings' -> 'From Email' address.

**Comment by mikeyhoward1977** [comment]
Its generally a good idea to use a separate email address to your normal admin email for email piping. Personally, I adjust my KB Support from address to match the address of the mailbox I have email piping pulling from.

However, if you want to keep them the same and use a single mailbox there are a couple of options already available;

1. Within Tickets -> Tools -> General you can enter a list of **banned emails**. When a form is submitted, if the email address matches an email within the banned emails list, it will not be processed. The Email Support plugin honours this list also whilst polling emails.

2. Alternatively, you can hook into a filter per [this example](https://gist.github.com/mikeyhoward1977/c193e1e1ef6de6515fdc7bc77826d129).

Will that give you what you need?

An enhancement we can make to the Email Support plugin would be to add an option to ignore emails with a specific string in the subject line. Any notifications you have going to the same address could then be updated to include this string.

**Comment by mikeyhoward1977** [comment]
@scottrpaterson ignore my last comment. I mis-understood.

**Comment by mikeyhoward1977** [comment]
We'll be introducing a textarea field within the Ticket Logged email setting section where you will be able to enter single addresses, or domains to which the Ticket Received emails should not be sent.

This seemed like a more viable option than simply not sending to the From email address as users may have other reasons for blocking this email notification to additional addresses.

**Comment by mikeyhoward1977** [comment]
Merged into version 1.2.8
