### ISSUE TITLE
Allow for link title of email tags

### ISSUE THREAD

**Issue by scottrpaterson** [KB-Support/kb-support#99]
In class-kbs-email-tags.php between lines 783 and 820, there are 3 functions which change the email tags such as {close_ticket_url} into links for the email.

Currently the link title is the URL and cannot be changed. It would be really nice for users to set your own URL.

I propose the following code change, which does not output an a href link. Therefore the user can choose to create a link in the settings editor using whatever title they want.

function kbs_email_tag_ticket_close_ticket_url( $ticket_id ) {
	$url = kbs_get_ticket_url( $ticket_id, false, true );
	$url = remove_query_arg( 'kbs_action', $url );
	$url = add_query_arg( 'kbs_action', 'close_ticket', $url );
	$url = apply_filters( 'kbs_tag_close_ticket_url', $url, $ticket_id );

	return $url;
} // kbs_email_tag_ticket_close_ticket_url

**Comment by mikeyhoward1977** [comment]
It will be difficult to simply change this as existing `{*_url}` tags will be impacted and no longer work for users as expected.

I will review other options but this would likely require a new tag (maybe more than one).
